x=input('Enter the first number: ')
x=int(x)
y=input('Enter the second number: ')
y=int(y)
print('Addition: ',x+y)
print('Subtraction: ',x-y)
print('Multiplication: ',x*y)
print('Division: ',x/y)